### ISSUE TITLE
Game freezes hitting (A) on Soul-Charged Sword

### ISSUE THREAD

**Issue by avidrissman** [Zelllll/tml#10]
v1.3, on OpenEmu 2.2.1, Mupen64Plus core 2.5.9

At the very start of the game get the Soul-Charged Sword. Open the menus, move the cursor to the Soul-Charged Sword, and just keep tapping (A). The game will lock up.

Video: https://youtu.be/jMtCC6RAGxA

Note that you can tell that the game locks up because the hearts in the upper left of the screen stop pulsing.

**Comment by MasterMathew** [comment]
I have this issue on real hardware through my Everdrive (v3) too. It only appears to happen at the very beginning after obtaining the Soul-Charged Sword. If I save before hand and then have it crash, upon reset the issue does not appear to resurface. 

Also, there is a minor difference in my issue, since I do not need to tap A over the soul-charged sword. I just need to hover over it from an item on the Equipment menu.

**Comment by Zelllll** [comment]
This is now fixed, and will be included in the 1.4 patch releasing tonight.
